version: "3.9"

services:
  weather-service:
    image: "tutkuince/weather-service:latest"
    build:
      context: .
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - "9595-9597:8080"
    environment:
      - "API_URL=${API_URL}"
      - "API_KEY=${API_KEY}"
    networks:
      - weather-service-network
  