version: "3.9"

services:
  weather-service:
    image: "tutkuince/weather-service:latest"
    build:
      context: .
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - "9595-9597:8080"
    environment:
      - "API_URL=${API_URL}"
      - "API_KEY=${API_KEY}"
    networks:
      - weather-service-network
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    networks:
      - weather-service-network
  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks:
      - weather-service-network



networks:
  weather-service-network: