version: "3.9"

services:
  weather-service:
    image: "tutkuince/weather-service:latest"
    build:
      context: .
    ports:
      - "9595:8080"
    environment:
      - "API_URL=${API_URL}"
      - "API_KEY=${API_KEY}"